spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
 
  resources:
    chain:
      compressed: true
      cache: true

  datasource:
    platform: h2
    url: jdbc:log4jdbc:h2:file:./h2/local
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password: sa

  h2:
    console:
      enabled: true
      path: /h2-console
mybatis:
  mapper-locations:
  - classpath:/mapper/**/*.xml

server:
  port: 8000
  servlet:
    session:
      cookie:
        name: SESSION_ID
    encoding:
      charset: UTF-8
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

logging:
  config: classpath:logback-spring.xml